---

- name: RedHat Family
  block:

    - name: Dnf-mark
      shell: dnf upgrade --exclude=perl
    
    - name: All packages RHEL 
      ansible.builtin.dnf:
        name: "*"
        state: latest  

    - name: Check if a reboot is needed on RHEL
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    
    - name: Reboot RHEL
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Delete kernels --oldkernels --count = 2
      shell: dnf remove --oldinstallonly installonly_limit = 2
  when:
    ansible_os_family == "RedHat"
    
- name: Debian Family
  block:
    - name: Apt-mark
      shell: apt-mark hold perl
    
    - name: All packages Deb
      ansible.builtin.apt:
        name: "*"
        state: latest
    
    - name: Check if a reboot is needed on Deb
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    
    - name: Reboot Deb
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
      
    - name: Delete cores --oldcores --count = 2
      shell: apt-get purge $(dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | head -n -1) && apt autoremove && update-grub
    
    - name: autoremove
      shell: apt autoremove

    - name: grub
      shell: update-grub

  when:
    ansible_os_family == "Debian"
    